story_list = [
    "Once upon a time, in a sunny meadow, there lived a little bunny named Bella. Bella loved to explore and make new friends. One day, while hopping through the meadow, she found a shiny, colorful egg hidden under a bush. Curious, Bella gently nudged the egg with her nose, and to her surprise, it began to crack open. Out popped a tiny, cheerful dragon named Draco. 'Hello!' Draco exclaimed. 'Thank you for finding me! I've been waiting for someone to help me find my way home.' Bella smiled and said, 'Don't worry, Draco. I'll help you!' And so, Bella and Draco set off on an adventure across the meadow. They met many friendly animals along the way who helped them with directions. They crossed a sparkling stream with the help of a wise old turtle, climbed a tall hill with the assistance of a strong deer, and finally reached a magical forest where Draco's family lived. Draco was overjoyed to be reunited with his family, and Bella was happy to have made a new friend. They promised to visit each other often and share many more adventures together. And so, Bella and Draco remained best friends, exploring the wonders of the meadow and the magical forest, living happily ever after.",
    
    "In a bustling forest, there was a tiny squirrel named Sammy. Sammy loved to collect acorns, but he was always careful to leave some for his friends. One day, he found a giant acorn, bigger than any he had ever seen. Excited, he tried to carry it home but it was too heavy. Along came his friends, a wise owl named Oliver and a kind-hearted mouse named Millie. They all worked together, and with their combined strength, they managed to roll the acorn back to Sammy's home. They had a wonderful feast, sharing the giant acorn with everyone in the forest. From that day on, Sammy, Oliver, and Millie were known as the best team in the forest, always ready to help one another and share the joys of life.",
    
    "Deep in the ocean, there was a young dolphin named Daisy. Daisy loved to swim fast and play with her friends. One day, she noticed a sad sea turtle named Timmy. Timmy had lost his way and couldn't find his family. Daisy decided to help Timmy. They swam through coral reefs, asked for directions from friendly fish, and avoided scary sharks. After a long journey, they found Timmy's family near a beautiful underwater cave. Timmy was overjoyed to be reunited with his family, and Daisy was happy to have made a new friend. They promised to visit each other often and explore the ocean together. And so, Daisy and Timmy became the best of friends, sharing many more underwater adventures.",
    
    "In a quiet village, there was a little girl named Lily who loved to paint. She painted beautiful pictures of flowers, trees, and animals. One day, she found an old, dusty paintbrush in her attic. When she used it, she discovered it was magical. Whatever she painted came to life! She painted a butterfly, and it flew around her room. She painted a garden, and flowers started to bloom. Lily was amazed and used her brush to make her village a more beautiful place. She painted new houses, gardens, and even a rainbow in the sky. The villagers were delighted and thanked Lily for bringing so much beauty and joy to their lives. Lily knew she had found her special gift, and she continued to use her magical paintbrush to make the world a brighter place.",
    
    "In a tall, tall tree, there lived a little bird named Benny. Benny dreamed of flying to the top of the tallest mountain. One day, he decided to follow his dream. He flew and flew, higher than he had ever flown before. Along the way, he met a friendly eagle named Ellie who decided to help him. Together, they soared through clouds and braved strong winds. Finally, they reached the top of the tallest mountain. Benny was thrilled and thanked Ellie for her help. From the top, they could see the whole world below them. Benny knew he could achieve anything if he believed in himself and had friends to help along the way. Benny and Ellie flew back home, excited to share their adventure with their friends.",
    
    "In a magical garden, there was a tiny fairy named Flora. Flora loved to take care of the flowers and plants. One day, she found a wilting flower that needed special care. Flora used her magic to water the flower and sang a beautiful song to it. Slowly, the flower began to bloom again. It turned out to be a magical flower that granted wishes. Flora made a wish for all the flowers in the garden to be healthy and happy. Her wish came true, and the garden became the most beautiful place in the fairy kingdom. All the fairies celebrated, and Flora was praised for her kindness and care. From that day on, Flora became the guardian of the magical garden, ensuring it always remained a place of beauty and joy.",
    
    "In a cozy little burrow, there lived a hedgehog named Henry. Henry loved to bake pies, and his pies were the best in the forest. One day, a new animal moved into the forest, a shy raccoon named Rachel. She had never tasted a pie before. Henry decided to welcome her with his special berry pie. He invited Rachel to his burrow and baked the pie with extra love and care. When Rachel tasted the pie, her eyes lit up with joy. She thanked Henry and they became fast friends. Rachel loved Henry's pies so much that they started baking together. They even opened a little pie shop in the forest, where all the animals came to enjoy their delicious treats. Henry and Rachel were happy, knowing they had brought a bit of sweetness to everyone's life.",
    
]